export const ERROR = 'ERROR'

export const CONFIGURE = 'CONFIGURE'
export const CONFIGURE_RETURNED = 'CONFIGURE_RETURNED'

export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const GET_VAULTS = 'GET_VAULTS'
export const VAULTS_RETURNED = 'VAULTS_RETURNED'

export const DEPLOY_VAULT = 'DEPLOY_VAULT'
export const DEPLOY_VAULT_RETURNED = 'DEPLOY_VAULT_RETURNED'

export const DEPOSIT_VAULT = 'DEPOSIT_VAULT'
export const DEPOSIT_VAULT_RETURNED = 'DEPOSIT_VAULT_RETURNED'

export const WITHDRAW_VAULT = 'WITHDRAW_VAULT'
export const WITHDRAW_VAULT_RETURNED = 'WITHDRAW_VAULT_RETURNED'

export const ADD_BORROWER = 'ADD_BORROWER'
export const ADD_BORROWER_RETURNED = 'ADD_BORROWER_RETURNED'

export const INCREASE_LIMITS = 'INCREASE_LIMITS'
export const INCREASE_LIMITS_RETURNED = 'INCREASE_LIMITS_RETURNED'

export const DECREASE_LIMITS = 'DECREASE_LIMITS'
export const DECREASE_LIMITS_RETURNED = 'DECREASE_LIMITS_RETURNED'

export const SEARCH_BORROWER = 'SEARCH_BORROWER'
export const SEARCH_BORROWER_RETURNED = 'SEARCH_BORROWER_RETURNED'

export const GET_BORROWER_VAULTS = 'GET_BORROWER_VAULTS'
export const GET_BORROWER_VAULTS_RETURNED = 'GET_BORROWER_VAULTS_RETURNED'

export const BORROW = 'BORROW'
export const BORROW_RETURNED = 'BORROW_RETURNED'

export const REPAY = 'REPAY'
export const REPAY_RETURNED = 'REPAY_RETURNED'

export const SET_BORROW_ASSET = 'SET_BORROW_ASSET'
export const SET_BORROW_ASSET_RETURNED = 'SET_BORROW_ASSET_RETURNED'

export const VAULT_CHANGED = 'VAULT_CHANGED'

export const SET_MODEL = 'SET_MODEL'
export const SET_MODEL_RETURNED = 'SET_MODEL_RETURNED'
